### ISSUE TITLE
верстка страницы с графиком (сводка)

### ISSUE THREAD

**Issue by Barcius** [data-prime/faberlic-front#1]

**Comment by Barcius** [comment]
надо поправить верстку

* побольше паддинг слева
* побольше паддинг между чекбоксами
* убрать перенос текста под круглую плашку
* убрать вертикальный скроллбар и поправить сайдбар

**Comment by alexyalinc** [comment]
> надо поправить верстку
> 
> * побольше паддинг слева
> * побольше паддинг между чекбоксами
> * убрать перенос текста под круглую плашку
> * убрать вертикальный скроллбар и поправить сайдбар

отправил pull request
